name: CI Workflow

on: 
    push:
        branches:
            - develop
            - feature/*
            - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, sit, uat]
    steps:
      - name: Code Checkout
        run: echo "Code Checkout from GitHub" 
      - name: Build
        if: github.base_ref == 'feature/*'
        run: echo "Building app to deploy on ${{ matrix.environment }}"
      - name: Test
        if: github.base_ref == 'feature/*'
        run: echo "Testing from ${{ matrix.environment }}"
      - name: Deploy
        if: github.base_ref == 'feature/*'
        run: echo "Deploy from ${{ matrix.environment }}" 



