name: CI Workflow

on: 
  push:
    branches:
      - develop
      - feature/*
      - release
      - main

jobs:
  ci-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: develop
            environment: dev
          - branch: feature/*
            environment: dev
          - branch: release
            environment: sit
          - branch: release
            environment: uat
          - branch: main
            environment: prod

    # Run this job only if the current branch matches the matrix.branch
    if: github.ref_name == matrix.branch || (startsWith(github.ref_name, 'feature/') && matrix.branch == 'feature/*')

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building app for ${{ matrix.environment }}"

      - name: Test
        run: echo "Testing on ${{ matrix.environment }}"

      - name: Deploy
        run: echo "Deploying to ${{ matrix.environment }}"


