name: CI Workflow

on: 
  push:
    branches:
      - develop
      - feature/*
      - release
  
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: Build Image and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: rehansayyed/to-do-app:latest
